# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec file for FilePilot AI"""

block_cipher = None

a = Analysis(
    ['filepilot/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('filepilot/resources', 'filepilot/resources'),
        ('filepilot/styles/themes', 'filepilot/styles/themes'),
    ],
    hiddenimports=[
        'filepilot.ai.base',
        'filepilot.ai.local_ai',
        'filepilot.ai.cloud_ai',
        'filepilot.ai.summarizer',
        'filepilot.app',
        'filepilot.cli',
        'filepilot.i18n',
        'filepilot.log',
        'filepilot.core.search_cache',
        'filepilot.core.file_scanner',
        'filepilot.core.duplicate_finder',
        'filepilot.core.file_organizer',
        'filepilot.core.indexer',
        'filepilot.core.file_watcher',
        'filepilot.core.task_queue',
        'filepilot.core.config',
        'filepilot.extractors.pdf_extractor',
        'filepilot.extractors.markdown_extractor',
        'filepilot.extractors.code_extractor',
        'filepilot.extractors.image_extractor',
        'filepilot.extractors.docx_extractor',
        'filepilot.extractors.xlsx_extractor',
        'filepilot.extractors.pptx_extractor',
        'filepilot.utils.file_utils',
        'filepilot.ui.tray',
        'filepilot.styles.manager',
        'whoosh',
        'whoosh.fields',
        'whoosh.index',
        'whoosh.qparser',
        'fitz',
        'PIL',
        'magic',
        'markdown',
        'yaml',
        'cryptography',
        'docx',
        'openpyxl',
        'pptx',
        'send2trash',
        'watchdog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'matplotlib', 'scipy', 'numpy',
        'pandas', 'torch', 'tensorflow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='FilePilot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'filepilot\resources\app.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='FilePilot',
)
